services:
  sec-db:
    image: postgres:15-alpine
    container_name: sec-db
    environment:
      POSTGRES_DB: sec
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - sec_db_data:/var/lib/postgresql/data
    networks:
      - sec-network

  app:
    build: .
    container_name: sec-app
    environment:
      DB_URL: jdbc:postgresql://sec-db:5432/sec
      DB_USERNAME: postgres
      DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - sec-db
    networks:
      - sec-network

volumes:
  sec_db_data:

networks:
  sec-network:
    driver: bridge